### PR TITLE
fix(pages): update search results filtering

### LINKED ISSUE #217: search bug: not showing results for health inspections
This search returns 1 result: https://data-sources.pdap.io/search/health/allegheny

I think it should return 3. These are all `approval_status: approved` and have similar but not duplicate URLs. I'm wondering if they're getting rejected as duplicates, though?

Screen Shot 2024-03-15 at 11 42 47 AM

### PR DESCRIPTION
**Pull request by joshuagraber**
- [ ] Accommodate multiple items of each record_type
- [ ] Resolves #217 

## To test
1. Run the app locally.
2. Navigate to [`/search/health/allegheny`](http://localhost:8888/search/health/allegheny)
3. Ensure 3 records are displayed (in contrast to [the same route in prod](https://data-sources.pdap.io/search/health/allegheny), which currently shows 1).

### CODE REVIEW

File: client/src/pages/SearchResultPage.vue [hunk 1]
```diff
@@ -110,7 +114,12 @@ export default {
 
 				// Format results into object keyed by record_type
 				const resultFormatted = res.data.data.reduce((acc, cur) => {
-					return { ...acc, [cur.record_type]: cur };
+					return {
+						...acc,
+						[cur.record_type]: Array.isArray(acc[cur.record_type])
+							? [...acc[cur.record_type], cur]
+							: [cur],
+					};
```
Comment (joshuagraber) [inline client/src/pages/SearchResultPage.vue:122]: @maxachis see this part of the code wrt bug fix for #217. The previous logic was keying an object by `record_type` but forgot to take into account that there might be multiple records of the same time. To fix this bug, we're instead assigning an array to each of those keys, to accommodate multiple values of each key. The updates to the `template` above are in service of this change (as well as some general cleanup, as we're moving away from the `GridContainer` and `GridItem` components).

Comment (maxachis) [reply client/src/pages/SearchResultPage.vue:120]: Ah, that would make sense. So regardless of whether there's one record or multiple, it is formatted into an array, simplifying the logic on the backend.

**Review by mbodeantor — APPROVED** [review]

File: client/src/pages/SearchResultPage.vue (hunk 1 above)
Comment (joshuagraber) [reply client/src/pages/SearchResultPage.vue:120]: > Ah, that would make sense. So regardless of whether there's one record or multiple, it is formatted into an array, simplifying the logic on the backend.

Yeah @maxachis I think @mbodeantor and I are aligned on the idea that the API should be as simple as possible, and any complex manipulation required by UX or design requirements should be handled by the client.
