### PR TITLE
Malformed url bug fix

### LINKED ISSUE #338: v1 bug: "view data source" link malformed
## Steps to reproduce

Make a search, like: https://data-sources.pdap.io/search/calls/all

The first source is "Calls for Service for Los Angeles Police Department - CA". If you click "view source", or source details then the URL, it takes you to https://data-sources.pdap.io/search/calls/data.lacity.org/resource/iy4q-t9vr.json

However, some links work OK—the next one over takes you to a [404 page](https://data.virginia.gov/Public-Safety/Open-View-Henrico-County-Calls-for-Service/g7aq-7uu3), but at least it's _their_ 404. Is it because we're missing an http(s)?

### PR DESCRIPTION
**Pull request by bonjarlow**
Fixes #338

`client/src/components/SearchResultCard.vue`
- javascript window.open() method assumes that without http(s):// it's a relative path. So this checks source_url and prepends https:// if not found.

`middleware/initialize_psycopg2_connection.py`
- explicitly load .env variables with dotenv

### CODE REVIEW

File: client/src/components/SearchResultCard.vue [hunk 1]
```diff
@@ -149,7 +149,11 @@ export default {
 			this.$router.push(`/data-sources/${this.dataSource.airtable_uid}`);
 		},
 		openSource() {
-			window.open(this.dataSource.source_url, '_blank');
+			let url = this.dataSource.source_url;
+			if (!/^https?:\/\//i.test(url)) {
+				url = 'https://' + url;
+			}
+			window.open(url, '_blank');
```
Comment (maxachis) [inline client/src/components/SearchResultCard.vue:156]: The regex pattern string here is going to be hard for someone not knowledgeable about regex/this code base/both to know what's going on.

In this case, I recommend doing one of two things:
1. Leaving a comment describing why this code is here and what it does
2. Extracting the complicated code to a separate method with a clear function name.

2 is my preference here, because this code is already heavily indented and such heavy indents can make the code more difficult to parse.

**Review by maxachis — APPROVED** [review]
Just implement one (or both!) of my two suggestions in the one comment I left, and we will be good!

File: client/src/components/SearchResultCard.vue (hunk 1 above)
Comment (maxachis) [reply client/src/components/SearchResultCard.vue:156]: For example, a method named `prepend_url_prefix_if_not_found()`
